# Generated by Django 3.1.7 on 2021-03-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekLCARS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='department',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.IntegerField(default=0),
        ),
    ]
