# Generated by Django 3.1.7 on 2021-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekLCARS', '0003_auto_20210305_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='rank',
        ),
        migrations.AddField(
            model_name='character',
            name='rankIMG',
            field=models.ImageField(blank=True, upload_to='rankIMG/'),
        ),
    ]
