# Generated by Django 3.1.7 on 2021-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekStories', '0003_auto_20210304_0302'),
        ('MoonTrekLCARS', '0004_auto_20210305_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='story',
            field=models.ManyToManyField(blank=True, related_name='characters', to='MoonTrekStories.MoonTrekStories'),
        ),
        migrations.AlterField(
            model_name='placesanditems',
            name='story',
            field=models.ManyToManyField(blank=True, related_name='places', to='MoonTrekStories.MoonTrekStories'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='story',
            field=models.ManyToManyField(blank=True, related_name='ships', to='MoonTrekStories.MoonTrekStories'),
        ),
    ]
