# Generated by Django 3.2.3 on 2021-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekLCARS', '0006_placesanditems_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='placesanditems',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ship',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
