# Generated by Django 3.2.3 on 2021-05-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekLCARS', '0007_auto_20210519_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='placesanditems',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='ship',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
    ]
