# Generated by Django 3.2.3 on 2021-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekLCARS', '0008_auto_20210520_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
