# Generated by Django 3.1.6 on 2021-02-09 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekBlog', '0002_auto_20210208_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
