# Generated by Django 3.1.7 on 2021-03-13 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoonTrekStories', '0003_auto_20210304_0302'),
        ('MoonTrekBlog', '0004_auto_20210209_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_story',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to='MoonTrekStories.MoonTrekStories'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
