# Generated by Django 3.2 on 2021-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekLCARS', '0006_placesanditems_type'),
        ('MoonTrekBlog', '0005_auto_20210312_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_character',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to='MoonTrekLCARS.Character'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_place',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to='MoonTrekLCARS.PlacesAndItems'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_ship',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to='MoonTrekLCARS.Ship'),
        ),
    ]
