# Generated by Django 3.2.3 on 2021-05-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekBlog', '0006_auto_20210510_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tags',
            new_name='seo_desc',
        ),
    ]
