# Generated by Django 3.1.7 on 2021-03-02 07:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonTrekStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='storyIMG')),
                ('series', models.IntegerField()),
                ('summary', tinymce.models.HTMLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MoonTrekChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.SlugField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='MoonTrekStories.moontrekstories')),
            ],
        ),
    ]
