# Generated by Django 3.1.7 on 2021-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekStories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moontrekstories',
            name='description',
            field=models.CharField(default='Please replace me.', max_length=255),
        ),
    ]
