# Generated by Django 3.1.7 on 2021-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekStories', '0002_moontrekstories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='moontrekchapters',
            name='epilogue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moontrekstories',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
