# Generated by Django 3.2 on 2021-05-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonTrekStories', '0005_auto_20210503_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
