# Generated by Django 3.1.6 on 2021-02-09 06:31

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MTBase', '0002_auto_20210208_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
