# Generated by Django 3.2.7 on 2021-09-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTBase', '0007_auto_20210520_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertText', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
