# Generated by Django 3.2.7 on 2021-09-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTBase', '0009_alter_landingalert_alerttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingalert',
            name='alertType',
            field=models.TextField(default='primary', max_length=50),
        ),
    ]
