# Generated by Django 3.2.7 on 2021-09-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTBase', '0010_landingalert_alerttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingalert',
            name='alertType',
            field=models.CharField(default='primary', max_length=50),
        ),
    ]
