# Generated by Django 3.2.7 on 2021-09-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTBase', '0011_alter_landingalert_alerttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingalert',
            name='alertText',
            field=models.TextField(max_length=350),
        ),
    ]
